plugins:
  - jekyll-redirect-from
  - jekyll-sitemap

permalink: /:title/

defaults:
    -
        scope:
            path: ""
        values:
            layout: default

url: https://pczerkas.github.io
title: pczerkas.github.io
#repo: weakish/micro-gh-page
